### ISSUE TITLE
Can you please add some screenshots/PDFs?

### ISSUE THREAD

**Issue by jelz** [MateuszKubuszok/B2BInvoiceTexTemplate#1]
Screenshot (e.g. in README) or sample PDF file would be really nice addition :tada:

**Comment by MateuszKubuszok** [comment]
Sample file available at: https://github.com/MateuszKubuszok/B2BInvoiceTexTemplate/releases/download/0.1/example.pdf but yes, I could make it more visible. :+1:

**Comment by jelz** [comment]
You're the boss :+1:
